# Generated by Django 2.2.17 on 2021-01-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
